# Generated by Django 3.1.7 on 2021-03-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=35)),
                ('calories_per_serving', models.IntegerField()),
                ('image', models.ImageField(upload_to='cook_app/images/lines')),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=35)),
                ('cooking_time', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='cook_app/images/recipes')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35)),
                ('discription', models.CharField(max_length=200)),
                ('order_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='cook_app/images/lines')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cook_app.recipe')),
            ],
            options={
                'db_table': 'recipe_line',
            },
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('measurement', models.CharField(blank=True, max_length=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cook_app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cook_app.recipe')),
            ],
            options={
                'db_table': 'ingredient_list',
                'unique_together': {('id', 'recipe', 'ingredient')},
            },
        ),
    ]
