# Generated by Django 3.1.7 on 2021-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cook_app/images/lines'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cook_app/images/recipes'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cook_app/images/lines'),
        ),
    ]
