# Generated by Django 3.1.7 on 2021-03-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook_app', '0002_auto_20210315_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cook_app/images/ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_app.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='recipe',
            field=models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.CASCADE, to='cook_app.recipe'),
        ),
    ]
